{application,mgd4erl,
             [{description,"An OTP library"},
              {vsn,"0.1.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[mgd4erl]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
